version: '3.8'

services:
  eth-node:
    image: ethereum/client-go:v1.10.15
    volumes:
      - ./data/nodes/eth/data:/root/.ethereum/
    ports:
      - "${ETH_SYNC_PORT:-30303}:30303"
      - "${ETH_RPC_PORT:-8545}:8545"
    stdin_open: true
    tty: true
    command: --http --http.addr 0.0.0.0 --http.api admin,debug,web3,eth,txpool,net,personal